### ISSUE TITLE
Would be nice if new deaths were printed in chat, like iChun's mod did

### ISSUE THREAD

**Issue by vizthex123** [syorito-hatsuki/death-counter#1]
As the title says, it'd be a nice feature rather than having to type `/deathcounter` each time.

**Comment by syorito-hatsuki** [comment]
Good think. When I have time I implement it

**Comment by vizthex123** [comment]
noice, thanks.

**Comment by vizthex123** [comment]
would also be nice if it didn't print the "webUI started" message every time you logged in. Maybe as a config option?

**Comment by syorito-hatsuki** [comment]
Added [indev](https://github.com/syorito-hatsuki/death-counter/commit/9426f867fb2e79f27f3e74e084cb5e26ba447e14). Soon release
