### ISSUE TITLE
Placeholders aren't replaced in some commands

### ISSUE THREAD

**Issue by srnyx** [syorito-hatsuki/death-counter#11]
**Mod version:** 2024.12.1
**Minecraft:** 1.21.4

- `/dcs <player>` doesn't work
- `/dcs top` works
- `/dcs <page>` doesn't work

![image](https://github.com/user-attachments/assets/9b26a1e4-3485-479f-b42f-28e4a218f798)
*Forgot to box the `%d` for page number*

**Comment by syorito-hatsuki** [comment]
I will check it with a ton of other projects next week. Share please latest.log file with that issue

**Comment by srnyx** [comment]
> Share please latest.log file with that issue

Client `latest.log`: https://mclo.gs/3ufNJXs
I don't have the logs of the server for some reason, tried looking in old logs folder but can't find it. *Mod is installed on server only, not client*

By the way, I stopped using the mod due to other reasons (just realized I didn't really need it), so I may not be able to continue testing if required.

**Comment by syorito-hatsuki** [comment]
https://modrinth.com/mod/death-counter/version/2024.12.3
