### ISSUE TITLE
Config file is always overridden with default values (2024.1.1 - 1.20.1)

### ISSUE THREAD

**Issue by Ergwano** [syorito-hatsuki/death-counter#13]
Changes to the `config.json` are always overridden with the default values on joining a world.
I can see this has been fixed in newer Minecraft versions of the mod already: https://github.com/syorito-hatsuki/death-counter/commit/ea5814a0ee4365d30d024f60b12afe2ec0f5b65d

Would it be possible to merge this and if possible other fixes back to the 1.20.1 version?

Thank you

**Comment by syorito-hatsuki** [comment]
Ye it in plan with some other issues that was fixed on new versions

**Comment by syorito-hatsuki** [comment]
# 2024.12.3
> 1.21.2+ https://modrinth.com/mod/death-counter/version/2024.12.3
> 1.21-1.21.2 https://modrinth.com/mod/death-counter/version/EoCndCSy
> 1.20.5-1.20.6 https://modrinth.com/mod/death-counter/version/vmcrJEIH
> 1.20.2-1.20.4 https://modrinth.com/mod/death-counter/version/uWsbvvRm
> 1.20-1.20.1 https://modrinth.com/mod/death-counter/version/VIplOeFK
