### ISSUE TITLE
Deaths should be counted per-world instead of being universal

### ISSUE THREAD

**Issue by vizthex123** [syorito-hatsuki/death-counter#4]
I noticed they're also saved in the config, which feels kind of odd.

But as the title says, it'd be nice if deaths were saved per-world instead of being universal. Makes it more accurate.

**Comment by syorito-hatsuki** [comment]
Whoops. My biggest mistake :) I going tomorrow doing a minor update. It gonna take from 3-7 work days. Sorry for the problems and thanks for reviewing it.

**Comment by syorito-hatsuki** [comment]
Stop. Did you mean per dimension?

**Comment by vizthex123** [comment]
> Stop. Did you mean per dimension?

no, per minecraft world.

**Comment by syorito-hatsuki** [comment]
Removed it to the hell :D
