### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by mrGRINCH** [syorito-hatsuki/death-counter#8]
Any chance you'd port this to Forge 1.18.2 as well?

Yours is the best deathcounter mod I've found.

**Comment by syorito-hatsuki** [comment]
> Any chance you'd port this to Forge 1.18.2 as well?
> 
> Yours is the best deathcounter mod I've found.

Hi. I don't have any plans about forge port.

Here is a mod from **ohaiiChun** it is available for 1.18.2: https://lcurseforge.com/minecraft/mc-mods/death-counter

**Comment by mrGRINCH** [comment]
No worries, just wanted to ask in case you'd consider it.

I have seen ohaiiChun's mod but it's not as nice as yours.

Thank you anyway.
